name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('apps/docs/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install docs dependencies
        working-directory: apps/docs
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        working-directory: apps/docs
        run: pnpm build

      - name: Deploy to Remote Host via SFTP
        uses: ticoraap/sftp-mirror@v1.6
        with:
          server: ${{ secrets.DOCS_SFTP_HOST }}
          user: ${{ secrets.DOCS_SFTP_USERNAME }}
          password: ${{ secrets.DOCS_SFTP_PASSWORD }}
          port: ${{ secrets.DOCS_SFTP_PORT }}
          local: './apps/docs/dist/'
          remote: '/'
