name: Release Please (V8)

on:
  push:
    branches:
      - v8

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: v8

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.GITHUB_TOKEN }}
