name: Prepare Release

on:
  pull_request:
    types: [closed]
    paths:
      - '**.json'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'release') && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest

    steps:
      - name: Delay
        run: sleep 2

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags (pre)
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Delay 2
        run: sleep 5

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Install dependencies
        run: pnpm --filter=\!{dill-pixel-docs,dill-pixel-examples-v8} install

      - name: Publish to npm
        run: pnpm run build-publish-all
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Remove .npmrc
        run: rm .npmrc

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update version"
          git push

      - name: Checkout repo 2
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Delay 3
        run: sleep 10

      - name: Send Google chat notification
        env:
          WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL -d '{
            "text": "A new Dill Pixel release just dropped! Check it out here: https://github.com/relishinc/dill-pixel/releases/tag/'$TAG_NAME'. Install using `npm install dill-pixel`"
          }'
