name: Release Please (V8)

on:
  push:
    branches:
      - v8

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Debug - List files
        run: ls -la

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - Check git status
        run: git status
