name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: main
          package-name: release-please-action
          token: ${{ secrets.GITHUB_TOKEN }}
