name: Prepare Release (V8)

on:
  pull_request:
    types: [closed]
    paths:
      - '**.json'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'release') && github.event.pull_request.base.ref == 'refs/heads/v8')
    runs-on: ubuntu-latest

    steps:
      - name: Delay
        run: sleep 10

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Checkout repo 2
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Publish to npm
        run: pnpm run build-publish-all
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update version"
          git push

      - name: Delay 2
        run: sleep 10

      - name: Send Google chat notification
        env:
          WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL -d "{
              \"text\": \"A new Dill Pixel release just dropped! Check it out here: https://github.com/relishinc/dill-pixel/releases/tag/$TAG_NAME\. Install using 'npm install dill-pixel"
          }"
